### ISSUE TITLE
Add find method for response codes

### ISSUE THREAD

**Issue by rverton** [dtag-dev-sec/explo#1]
There needs to be a way to define a check for a response code.

Example usecase: Check if a request to /admin/foo returns a 500:

```
name: exploit
description: checks if a request to /admin/foo returns a status code 500
module: http
parameter:
    url: http://example.com/admin/foo
    find_response_code: 500
```
