### ISSUE TITLE
Additional informative fields

### ISSUE THREAD

**Issue by ilyaglow** [dtag-dev-sec/explo#2]
Hey there,

Firstly I'd like to thank you for this project and for the awesome idea behind it.

During integration explo as a library in the workflow I faced a problem - explo seems very restrictive about fields included and lacks "informative" fields for the whole multistaged exploit, like a _hostname_ affected, _CVSS_, a high-level _overall description_ and other _customized_ fields.

This informative fields could be in the additional yaml object on top of the file or something like that, what you think?

**Comment by rverton** [comment]
Hey @ilyaglow,
first of all thanks for your feedback. I really appreciate the interest in this project!

We currently use an own (workflow/vulnerability management) platform on top of explo which saves  additional metadata like the fields you mentioned. We separated vulnerability data and meta data this way, but I agree with you that there should be some general customizable fields to define additional data to be able to extend this.

Do you have a suggestion? I think I will also find some time around new year to think over this and make some drafts. I prefer a solution which is backwards compatible to the current format.

Greetings,
robin

**Comment by ilyaglow** [comment]
Thanks for sharing this! I might try to create a new tiny package to handle this like you do :)

I made a [little experimental branch](https://github.com/ilyaglow/explo/commit/2bdb82481baa74631fdec497e6d03c71be5d3442) yesterday but it's not backward compatible so it doesn't fit well. Probably we can add a new function to core that will work with a new format and add an appropriate switch to explo cli tool.

**Comment by rverton** [comment]
So I had some time to look over your branch now. Actually I'm fine with the explo **library** not being backwards compatible (we are still in an experimental state with this library). What's important for me is that this change is not going to break old .yaml files, because otherwise people using it will have to change all their old vulnerability definition files.

As I can see in your branch, you are adding the info fields to the first block in the .yaml file. Thats fine to me. But maybe we should group this fields, so we do not limit the user to what additional fields he can use (like hostname and CVSS in your example)? Maybe something like this:

```yaml
name: login
description: login with test credentials
module: http
metadata:
    cvss: 8.9
    author: Foo Bar
parameter:
    url: http://testphp.vulnweb.com/userinfo.php
    method: POST
    body:
        uname: test
        pass: test
```

Another solution which comes to my mind is using a new module. Using this is a bit more verbose (more lines) and can look like this:

```yaml
name: metadata
description: define metadata
module: metadata
parameter:
    cvss: 8.9
    author: Foo bar
---
[...]
```
