### ISSUE TITLE
Json-like data in POST 

### ISSUE THREAD

**Issue by MonaxGT** [dtag-dev-sec/explo#3]
Hello, 

Can you add json-like data in POST message? 

like this:
```
payload = {'some': 'data'}
r = requests.post(url, json=payload)
```

**Comment by rverton** [comment]
Hi @MonaxGT,
you can already do it this way:
```yaml
name: json
description: Test JSON
module: http
parameter:
    url: https://httpbin.org/post
    method: POST
    headers:
        Content-Type: application/json
    body: '{"foo":"bar"}'
```
Result:
```
$ explo /tmp/explo-json.yaml -v
Loading /tmp/explo-json.yaml
---
Block json: Test JSON
HTTP Response: 200 (365 bytes)

POST https://httpbin.org/post HTTP/1.1
Content-Type: application/json
Content-Length: 13

{"foo":"bar"}

HTTP/1.1 200 OK
Connection: keep-alive
Server: meinheld/0.6.1
Date: Sun, 11 Mar 2018 14:38:46 GMT
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Powered-By: Flask
X-Processed-Time: 0
Content-Length: 365
Via: 1.1 vegur

{
  "args": {}, 
  "data": "{\"foo\":\"bar\"}", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept-Encoding": "identity", 
    "Connection": "close", 
    "Content-Length": "13", 
    "Content-Type": "application/json", 
    "Host": "httpbin.org"
  }, 
  "json": {
    "foo": "bar"
  }, 
  "origin": "93.244.131.236", 
  "url": "https://httpbin.org/post"
}

==> Success.
```
