### ISSUE TITLE
Open Redirect

### ISSUE THREAD

**Issue by doomguy** [dtag-dev-sec/explo#4]
Hi,

is there a way to check for the actual contents of a return header? This would be helpful to test for Open Redirect vulnerabilities.

Example Explo file:
```
name: Open Redirect
description: example.com - Open Redirect via Callback parameter
module: http
parameter:
    url: https://www.company.com/login.html?Callback=https://example.com
    method: GET
    headers:
        User-Agent: Mozilla/5.0
    expect_response_code: 302
    headers_required:
        Location: https://example.com
```
