### ISSUE TITLE
header_required seems to be broken

### ISSUE THREAD

**Issue by doomguy** [dtag-dev-sec/explo#5]
Hi,

the method "headers_required" always returns "success" for me.

```
name: headers_required broken
description: headers_required always returns success
module: http
parameter:
    url: https://www.example.com
    method: GET
    headers:
        User-Agent: Mozilla/5.0
    headers_required:
        iDontExist: .
```
```
 % explo headers.explo 
Loading headers.explo
---
Block headers_required broken: The header_required method seems to be broken
HTTP Response: 200 (1256 bytes)
==> Success.
```

Am I missing something here or is it broken somehow?

**Comment by rverton** [comment]
Hi @doomguy,
I just commited a fix for this.

Please also make sure to use the correct module for headers (`header` instead of `http`):

```
name: headers_required broken
description: headers_required always returns success
module: header
parameter:
    url: https://www.example.com
    method: GET
    headers:
        User-Agent: Mozilla/5.0
    headers_required:
        iDontExist: .
```
